[platformio]
default_envs = r1

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
monitor_filters = direct, time, esp32_exception_decoder
lib_deps =
    https://github.com/F-Army/arduino-dw1000-ng.git
build_flags =
    -I include
    -D CORE_DEBUG_LEVEL=3
    -O2

; ----------------------------------------------------------------------
; Robot 1: ESP32-S3-WROOM-1-N8R2 (8MB Flash QIO, 2MB Quad-PSRAM QSPI)
; ----------------------------------------------------------------------
[env:r1]
board = esp32-s3-devkitc-1
board_build.flash_size = 8MB
board_build.arduino.memory_type = qio_qspi
build_flags =
    ${env.build_flags}
    -D ROBOT_ID=1
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; ----------------------------------------------------------------------
; Robot 2: ESP32-S3-WROOM-1-N16R8 (16MB Flash QIO, 8MB Octal-PSRAM OPI)
; ----------------------------------------------------------------------
[env:r2]
board = esp32-s3-devkitc-1
board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
build_flags =
    ${env.build_flags}
    -D ROBOT_ID=2
    -D BOARD_HAS_PSRAM

; ----------------------------------------------------------------------
; Robot 3: ESP32-S3-WROOM-1-N16R8 (16MB Flash QIO, 8MB Octal-PSRAM OPI)
; ----------------------------------------------------------------------
[env:r3]
board = esp32-s3-devkitc-1
board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
build_flags =
    ${env.build_flags}
    -D ROBOT_ID=3
    -D BOARD_HAS_PSRAM

; ----------------------------------------------------------------------
; Robot 4: ESP32-S3-WROOM-1-N16R8 (16MB Flash QIO, 8MB Octal-PSRAM OPI)
; ----------------------------------------------------------------------
[env:r4]
board = esp32-s3-devkitc-1
board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
build_flags =
    ${env.build_flags}
    -D ROBOT_ID=4
    -D BOARD_HAS_PSRAM
